pipeline {
    agent any

    stages {
        stage('One') {
            steps {
                echo 'Hello World'
            }
        stage('Two') {
            steps {
                echo 'Wrapping up'
            }
            
        }
    }
    
    post {
        always {
            echo "Done!"
        }
    }
}

